- platform: switch
  name: Couch Light
  entity_id: switch.couch_ceiling
- platform: switch
  name: Table Light
  entity_id: switch.table_ceiling
- platform: switch
  name: Sink Light
  entity_id: switch.06003002cc50e37f5432_1
- platform: switch
  name: Counter Light
  entity_id: switch.06003002cc50e37f5432_2
- platform: switch
  name: Kitchen Light
  entity_id: switch.kitchen_ceiling
- platform: switch
  name: Desk Light
  entity_id: switch.bf0c3986535c3a94f4q0qr